### PR TITLE
getStockValues.py

### PR DESCRIPTION
**Pull request by parallelipopat**

### CODE REVIEW

**Review by NickHu — COMMENTED** [review]
Please end files with a single newline, use a space after a opening a comment and after a comma separating arguments. Also don't rely on Python allowing variables to fall through scope - it's horrible style.
Please stick to 2-space indentation.

**Comment by NickHu** [comment]
Can you provide an example of this working? I couldn't get it to work calling it like:
`python3 getStockValues.py GOOG 2016-12-24 2016-12-27 daily 0`. I suspect what is happening is I'm hitting the rate limit and it's not being caught properly.

**Comment by parallelipopat** [comment]
I ran your command `python getStockValues.py GOOG 2016-12-24 2016-12-27 daily 0` and got `[["2016-12-27", "2016-12-27"]]`

**Comment by NickHu** [comment]
Could you try it repeatedly until you hit the rate limit and see what happens? I think it's 50 requests in an hour

**Comment by parallelipopat** [comment]
I've done a couple of trials, and I keep on getting a 429 error that is caught. Could you tell me what exactly was the error that you were getting?
50 is the limit for anonymous calls, but when we had the API key, that should not be a problem as we will have 50,000 calls a day then.

**Comment by NickHu** [comment]
Do we still need this?

**Pull request closed without merging**
